# Generated by Django 4.1.7 on 2023-02-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=50, unique=True)),
                ('aadhaar_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], default='Permanent', max_length=200)),
                ('employee_type', models.CharField(choices=[('Tailor', 'Tailor'), ('Cutting Master', 'Cutting Master')], default='Cutting Master', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
